version: 2
updates:
  - package-ecosystem: "go:modules"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      include: scope
    assignees:
      - abyanmajid
    reviewers:
      - abyanmajid
